### ISSUE TITLE
"phread.h" not found

### ISSUE THREAD

**Issue by gkorland** [WebAssembly/wasi-libc#155]
How to include the libc-top-half in the build process and get it in sys_root?

**Comment by sbc100** [comment]
WASI doesn't currently support threads.   You can build wasi-libc with THREAD_MODEL=posix, which will get you pthread.h, but you won't get something with working threading because we don't have any APIs yet for creating threads.

If you are interesting in pushing for threading APIs when the main WASI repository is probably the best place to do that.

**Comment by sunfishcode** [comment]
See also the discussion in https://github.com/WebAssembly/threads/issues/138 for more background on the core spec work needed to enable threads.
