### ISSUE TITLE
No test suite?

### ISSUE THREAD

**Issue by syrusakbary** [WebAssembly/wasi-libc#182]
I just encountered this issue #180 and I was surprised to find that there is no test suite for this WASI libc.

I think if we want to evolve WASI at a healthy pace, it will be necessary a test-suite for it, assuring that there are no unintended breaking changes moving forward.

**Comment by MarkMcCaskey** [comment]
I believe the relevant tests are in the [wasi-sdk repo](https://github.com/WebAssembly/wasi-sdk/tree/master/tests) and the test for #181 was added in https://github.com/WebAssembly/wasi-sdk/pull/95.

But to be fair the only reason I know this is because someone happened to bring up this bug in conversation yesterday.  It's not obvious from just looking at the repo itself.

**Comment by syrusakbary** [comment]
Oooops. Didn't realize there were already tests. Perhaps might be a good idea to increase visibility on those.
