### ISSUE TITLE
Make dlmalloc optional

### ISSUE THREAD

**Issue by aykevl** [WebAssembly/wasi-libc#244]
This is perhaps a more minimal version of issue #94.

I would like to use a custom allocator because the environment I'm using wasi-libc in (TinyGo) already implements a heap. I think the easiest way to get that working is to not compile dlmalloc as part of wasi-libc.

Any idea how this might be implemented? I'm hitting issues with the file `undefined-symbols.txt` when I comment out the wrapper functions in `dlmalloc/src/dlmalloc.c`.

**Comment by sunfishcode** [comment]
Other parts of libc depend on having a `malloc` and similar functions; does your allocator provide `malloc`-compatible symbols?

**Comment by aykevl** [comment]
I found that I can simply define the functions in my application and they will override the functions defined in the library. I already knew this, just didn't realize it would apply here.

Here is how I did it: https://github.com/tinygo-org/tinygo/pull/1992

> Other parts of libc depend on having a `malloc` and similar functions; does your allocator provide `malloc`-compatible symbols?

Sort of, I've implemented the necessary wrapper functions in the PR above. It's a GC and `free` doesn't currently do anything, but that's fine.

**Comment by PiotrSikora** [comment]
Could we reopen this isssue? I think the ability to link another allocator would be useful.

Notably, using [`wee_alloc`](https://github.com/rustwasm/wee_alloc), [`mimalloc`](https://github.com/purpleprotocol/mimalloc_rust) or another `#[global_allocator]` in Rust works fine for `wasm32-unknown-unknown` targets, but `wasi-libc` always pulls `dlmalloc` when building for `wasm32-wasi` target, which results in multiple allocators in the Wasm bytecode, reintroducing large codebase which removal was one of the main reasons (small code size) for creating `wee_alloc` in the first place.

**Comment by sbc100** [comment]
I would hope that the approach @aykevl uses should be enough to completely override/replace dlmalloc, no?    Just providing your `-lmymalloc` library on the command line should be enough I think?

**Comment by sunfishcode** [comment]
Yes, `-lmymalloc` should work. That said, it'd be great for wasi-libc to have alternative malloc options available. `dlmalloc` is several kilobytes of code.

**Comment by PiotrSikora** [comment]
`-lmymalloc` might work with extra care, but if we know that the embedding application is going to use custom allocator, then building `dlmalloc` seems wasteful. Also, the ABI surface isn't very clear (is it only `malloc`, `calloc`, `realloc` and `free`, or do we also need to override `malloc_usable_size` and other functions?), and missing even one of those functions results in `dlmalloc` being included even with `-lmymalloc`.

Basically, what I'm asking for is for wasi-libc to build with `make BUILD_DLMALLOC=no`.

It's not only about the extra code size, but also because the interaction between multiple allocators seems a bit tricky. If I'm reading this right, `try_init_allocator` in wasi-libc assumes that `dlmalloc` is the only allocator (or at least, the first allocator being called), and that the memory between `__heap_base` and the end of linear memory is free at the time of the first call to `dlmalloc`, which isn't true when multiple allocators are operating in the same memory space.

**Comment by aykevl** [comment]
> Also, the ABI surface isn't very clear (is it only `malloc`, `calloc`, `realloc` and `free`, or do we also need to override `malloc_usable_size` and other functions?), and missing even one of those functions results in `dlmalloc` being included even with `-lmymalloc`.

Yes, that's what I'm worried about as well. To be somewhat defensive, I've implemented all of them in https://github.com/tinygo-org/tinygo/pull/1992 (`malloc`, `calloc`, `realloc`, `free`, `posix_memalign`, `aligned_alloc`, `malloc_usable_size`), most of which simply exit with an error message.

I'll reopen this to get `make BUILD_DLMALLOC=no` to work. I'd feel safer if the dlmalloc functions were not included in the library at all.

**Comment by sbc100** [comment]
I don't see any issue with providing that option.

It would make the resulting libc somewhat odd, since normally malloc is expected to be defined in libc, but since the official version of the SDK won't use this option I don't see much harm.

**Comment by aykevl** [comment]
I have made a PR here: https://github.com/WebAssembly/wasi-libc/pull/250

**Comment by lygstate** [comment]
Merged,  can this to be closed?

**Comment by sunfishcode** [comment]
Yes, thanks!
