### ISSUE TITLE
wasi-libc issue with stdio header files on browser

### ISSUE THREAD

**Issue by mrrostam** [WebAssembly/wasi-libc#248]
Hello folks,

I am using `wasi-libc` to provide the standard C library for my browser-based application centered on [this article](https://depth-first.com/articles/2019/10/16/compiling-c-to-webassembly-and-running-it-without-emscripten/) (So I am not using `wasmtime`).

I compiled my program using the following command:
`clang --target=wasm32-wasi --sysroot ... -nostartfiles -Wl,--no-entry -Wl,--export-all -Wl,--lto-O2 -Wl,--allow-undefined -Wl,--import-memory main.c -o main.wasm`

Everything seemed fine till I tried to use some function inside the `stdio` header file (e.g., `vsnprintf`); then I got a runtime error like below:
`Import #1 module="wasi_snapshot_preview1" error: module is not an object or function`

After investigating this issue and looking into the WAT file, I realized that many functions related to file operations are imported into the wasm file and are defined nowhere. something like:
`(import "wasi_snapshot_preview1" "fd_pread" (func (;18;) (type 7)))`

So I manually added these functions in the js file:
```js
const wasi_snapshot_preview1_emulator = {
    fd_pread: input => {
        return 0;
    },
    ...
}
```
and passed them to the wasm file using `ImportObject`.

Now it's working again without any specific issue, but the solution is kind of hacky.
I wonder if there is a way to stop the compiler from importing these unneccessary functions in the first place?

**Comment by sbc100** [comment]
If you want to load wasm files build with wasi-sdk (or otherwise built against wasi-libc) you need to provide and implementation of the WASI APIs.   Rather than write one yourself you can use of the one existing ones such as the one provided by recent versions of node:  https://nodejs.org/api/wasi.html.   If you are running on the web you will need some kind of web implementation/polyfil.

**Comment by mrrostam** [comment]
@sbc100 thanks for the help. One question, is there any way for me to implement them in wasm rather than using some external APIs in JS?

**Comment by sbc100** [comment]
You might be able to implement some kind of null/polyfill versions that do nothing in wasm itself, but that it unlikely to be very useful.   In general, WASI exists in order interface with the outside world (the system) and perform tasks and WebAssembly on its own cannot perform.   In the case of a JS environment the "system" is JS and its likely JS will be needed in order to implement the system calls.
