### ISSUE TITLE
wasm-ld: error: import module mismatch for symbol: __wasi_proc_exit

### ISSUE THREAD

**Issue by glandium** [WebAssembly/wasi-libc#258]
After 2b7e73ae7ac0bad6391d89cc3274a28412243389, linking a rust wasi staticlib to C code fails with:
```
wasm-ld: error: import module mismatch for symbol: __wasi_proc_exit
>>> defined as env in /home/glandium/.mozbuild/sysroot-wasm32-wasi/lib/wasm32-wasi/crt1.o
>>> defined as wasi_snapshot_preview1 in /tmp/central/obj-wasm32-unknown-wasi/wasm32-wasi/release/libjsrust.a(_Exit.o)
```
(this comes from building spidermonkey with current wasi-sdk (that was recently updated to current wasi-libc))

STR:
```
$ cargo new foo --lib
$ cd foo
$ cat >> Cargo.toml <<EOF
[lib]
crate-type = ["staticlib"]
EOF
$ cat > src/lib.rs <<EOF
#[no_mangle]
pub extern "C" fn foo() {
    println!("Hello, world!");
}
EOF
$ cargo build --target=wasm32-wasi
$ cat > foo.c <<EOF
extern void foo();

int main() {
  foo();
  return 0;
}
EOF
$ clang -o foo foo.c target/wasm32-wasi/debug/libfoo.a --target=wasm32-wasi --sysroot=/path/to/wasi-sysroot
wasm-ld: error: import module mismatch for symbol: __wasi_proc_exit
>>> defined as env in /home/glandium/.mozbuild/sysroot-wasm32-wasi/lib/wasm32-wasi/crt1.o
>>> defined as wasi_snapshot_preview1 in target/wasm32-wasi/debug/libfoo.a(_Exit.o)
```

Cc: @alexcrichton

**Comment by alexcrichton** [comment]
One of the more likely sources for a mismatch like this is a mismatch between rustc's bundled libc version and the version of wasi-sdk. If Rust code is being linked to externally compiled wasi it's recommended to compile with `-C target-feature=-crt-static` to cause Rust to use the system libc instead of its bundled one. 

Can you post the version of Rust that you're using which generates this mismatch?

**Comment by glandium** [comment]
1.55.0 and nightly (308dffd25 2021-09-22)

**Comment by glandium** [comment]
`-C target-feature=-crt-static` works. Thank you.
