### ISSUE TITLE
Support for `accept{,4}`

### ISSUE THREAD

**Issue by rvolosatovs** [WebAssembly/wasi-libc#284]
With #282 in place, it should be now possible to implement `accept` and `accept4`.

**Comment by rvolosatovs** [comment]
cc @Deepansharora27 perhaps you could be interested in contributing to this?

**Comment by Deepansharora27** [comment]
@rvolosatovs Apologies Roman, I missed the notification of you tagging me here 😅

I thought you were working on this for the `0.4` release so I thought to not work on this then. 

Apologies again for missing the tag message

**Comment by Deepansharora27** [comment]
https://github.com/WebAssembly/wasi-libc/blob/7302f33f99233482de8eedfcd21495c20858e0e4/libc-top-half/musl/src/network/accept.c#L1-L7

https://github.com/WebAssembly/wasi-libc/blob/7302f33f99233482de8eedfcd21495c20858e0e4/libc-top-half/musl/src/network/accept4.c#L7-L19

As I was iterating and trying to get an understanding of the repository, I have found prototype implementations of both the `accept()` and `accept4()` functions. 
Since the issue description entails that the required task is to add support for `accept()` and `accept4()`, I am not sure,How can I take this ahead from here given that these two are the prototype implementations for the function.

**Comment by sunfishcode** [comment]
Those accept.c and accept4.c files are in the libc-top-half/musl directory and are part of musl. musl upstream only supports Linux, so to make it work for wasi, we only use musl's "top half"&mdash;things like printf, qsort, etc.&mdash;and disable its "bottom half&mdash;things like read, open, but also accept and accept4 as seen here. Specifically, in the code in these musl files, `socketcall_cp` and `__syscall` perform Linux syscalls, so the code won't work as-is.

For wasi-libc, we'll need to add libc-bottom-half/sources/accept.c and libc-bottom-half/sources/accept4.c, which likely do something similar, but which call the WASI functions instead of doing Linux syscalls. Also, WASI doesn't have `O_CLOEXEC` (as it doesn't have an `exec`), so it doesn't need `SOCK_CLOEXEC`/`FD_CLOEXEC` code.
